### ISSUE TITLE
Handcrafted Issue

### ISSUE THREAD

**Issue by ereese99** [MehVahdJukaar/sleep_tight#13]
I can't edit my handcrafted bedsheets with this mod installed

**Comment by MehVahdJukaar** [comment]
does it only work at night? does it work with shift clicking?

**Comment by ereese99** [comment]
Unfortunately it doesn't work while shift-clicking or at different points during the day. Using newest Fabric versions of both mods on Fabric 0.14.17

**Comment by MehVahdJukaar** [comment]
hm thats very weird the mod event shouldnt evne trigger when shitfing. does it happen when you have blocks above the bed too? I'll test this out in a bit

**Comment by MehVahdJukaar** [comment]
try new version
