### ISSUE TITLE
incompatibility

### ISSUE THREAD

**Issue by Willem07** [MehVahdJukaar/sleep_tight#19]
![image](https://user-images.githubusercontent.com/51959206/227735460-9455a73e-9555-43dd-ae13-16d09455a18b.png)

**Comment by MehVahdJukaar** [comment]
Send log

**Comment by Willem07** [comment]
[2023-03-26-1.log](https://github.com/MehVahdJukaar/sleep_tight/files/11071677/2023-03-26-1.log)
Mods are compatible and also compatible with the sounds physics mod, but the modpack crashes when sleep tight and more babies are together

**Comment by MehVahdJukaar** [comment]
i see that some mod (presumibly more babies) is forcefully loading my configs on mod construct. That fails as they require registration to have happened. on forge configs are loaded (by forge) after registration for this reason

**Comment by MehVahdJukaar** [comment]
yeah found this in their code

"

        // MAYBE YOU ARE NOT SUPPOSED TO DO THIS
        ConfigTracker.INSTANCE.loadConfigs(ModConfig.Type.COMMON, FMLPaths.CONFIGDIR.get());
       
      "
      which is self explanatory. they should at most load their own configs and that's not even the way to do it

**Comment by MehVahdJukaar** [comment]
send the other log pls

**Comment by Willem07** [comment]
What other logs? Minecraft does not want to start, I will try to find another mod because of which this conflict occurs

**Comment by MehVahdJukaar** [comment]
you said there also was something with sound physics

**Comment by MehVahdJukaar** [comment]
nevermind i misread

**Comment by Willem07** [comment]
A very strange mistake, I can't understand it. As soon as more than 21 mods are added to the mods folder, an error occurs and it doesn't matter which mod, absolutely any, but if there are less than 21 of any mod in the modpack, everything works!
[latest.log](https://github.com/MehVahdJukaar/sleep_tight/files/11073319/latest.log)

Look at which mods I started checking the conflict with, but I think it doesn't matter
![Unnamed](https://user-images.githubusercontent.com/51959206/227811276-21022ba5-4e32-441f-96b8-e655d5af29ab.png)

**Comment by Willem07** [comment]
I'm sorry if I'm not explaining it clearly. I don't speak English

**Comment by Willem07** [comment]
In any case, if this is a problem on the side of the more babies mod, I won't use it

**Comment by MehVahdJukaar** [comment]
yeah i reported it to them. I was en experimental changes taht they did which broke stuff so i would expect them to fix it soonish. anyways ty
