### ISSUE TITLE
1.18.2 Fabric Backport?

### ISSUE THREAD

**Issue by ConqAra** [MehVahdJukaar/sleep_tight#23]
Is a 1.18.2 backport in the works or planned? If not, would it be possible for you to make one?

**Comment by MehVahdJukaar** [comment]
sorry i dont have time for backports. it would require me to backport all its dependencies too which would require a lot of time id rather spend on updating or more fun stuff like adding new content. beside mod doesnt seem to be that popular now

**Comment by ConqAra** [comment]
fair enough
