### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by Willem07** [MehVahdJukaar/sleep_tight#24]
Please make compatibility more comfortable in a multiplayer game
![2023-04-07_00 40 50](https://user-images.githubusercontent.com/51959206/230500018-5b35bd4c-09c5-4107-9e5a-65c209f0860c.png)
![2023-04-07_00 42 13](https://user-images.githubusercontent.com/51959206/230500038-8a5dcf10-1ce1-4eda-a66f-1a347d089f9b.png)
![2023-04-07_00 42 53](https://user-images.githubusercontent.com/51959206/230500045-33f3a7b0-5dfa-434c-9f13-d61a6dff7ac3.png)
![2023-04-07_00 43 10](https://user-images.githubusercontent.com/51959206/230500081-1ae85047-0493-4866-845d-06fa90fee34e.png)
![2023-04-07_00 43 19](https://user-images.githubusercontent.com/51959206/230500088-2cd978ba-ff52-4c48-b69e-cad162d2128a.png)
![Unnamed](https://user-images.githubusercontent.com/51959206/230500102-e9c7b787-e843-40cd-a6d5-4e60ded4d4ff.png)

**Comment by MehVahdJukaar** [comment]
never had anybody to test this with ;-;

**Comment by MehVahdJukaar** [comment]
ok try with new version. should work as intented now, heart particle and regen effect too
