### ISSUE TITLE
[1.19.2] Incompat with Better Respawn?

### ISSUE THREAD

**Issue by HockeyZman2000** [MehVahdJukaar/sleep_tight#26]
[latest.log](https://github.com/MehVahdJukaar/sleep_tight/files/11360220/latest.log)

Upon dying and respawning, I appear to be stuck inside of myself? It's like I can look around using F5 and attack myself as well. My best guess is that both mods are somehow conflicting over a death event.
Using Sleep Tight alone, I die and everything is normal when I respawn. Using Better Respawn alone also is normal. This only happens when I have the two installed together.

**Comment by MehVahdJukaar** [comment]
Are you sure it's not thirst mod? I see something related to that

**Comment by MehVahdJukaar** [comment]
I tried this and i cant replicate it

**Comment by HockeyZman2000** [comment]
[latest.log](https://github.com/MehVahdJukaar/sleep_tight/files/11361943/latest.log)

Just attempted again without the thirst mod installed, still having the same problem. I've also tried removing mods that involve network connection changes as I seen those mentioned in the log.

I've also went ahead and tried it only installing Sleep Tight, Moonlight, and Better Respawn and got this log here:
[latest.log](https://github.com/MehVahdJukaar/sleep_tight/files/11361998/latest.log)

I'm able to move around after I die the very first time, but after that I'm not able to break any blocks nor die a second time. Tick speed is still normal because I see other entities moving around like normal

**Comment by MehVahdJukaar** [comment]
I see what's going on

**Comment by MehVahdJukaar** [comment]
Can you confirm it works for you now?

**Comment by HockeyZman2000** [comment]
Both problems are now fixed! Thank you! Now to figure out the other things wrong with my pack lol :)
