### ISSUE TITLE
Crash on startup [1.19.4 Fabric]

### ISSUE THREAD

**Issue by JoostMSoftware** [MehVahdJukaar/sleep_tight#27]
Hello, I was interested in your mod Sleep Tight and wanted to make a pack around it, but I got a crash upon startup. 

Mod version used: 1.19.4-1.0.20

Crash log: 
[crash-2023-05-11_16.14.57-client.txt](https://github.com/MehVahdJukaar/sleep_tight/files/11453086/crash-2023-05-11_16.14.57-client.txt)

Latest log: 
[latest.log](https://github.com/MehVahdJukaar/sleep_tight/files/11453091/latest.log)

I apologise if this error is on me, tho wanted to share this none the less. Have a pleasant day <3

**Comment by MehVahdJukaar** [comment]
fixed

**Comment by JoostMSoftware** [comment]
awesome thanks, with this I will close this issue then!
