### ISSUE TITLE
Respawn anchor doesn't work

### ISSUE THREAD

**Issue by linkovich2** [MehVahdJukaar/sleep_tight#35]
Tested in 1.19.2 / Forge 43.2.14 / Mod version 1.0.22 / Moonlight 2.2.40 with only JEI added.

Was trying to figure out what caused respawn anchors not to work in my world and finally landed on testing sleep tight. Turns out it was this. Not sure if that's intended or not

**Comment by MehVahdJukaar** [comment]
Fixed

**Comment by linkovich2** [comment]
Damn that was lightspeed

**Comment by linkovich2** [comment]
That did the trick

**Comment by MehVahdJukaar** [comment]
Nice. Ye won't let my favourite mod have a game breaking bug
