### ISSUE TITLE
[Fixed, newest version]1.20.1 Not compatible with 1.20.1

### ISSUE THREAD

**Issue by Zunwolf1896** [MehVahdJukaar/sleep_tight#37]
![image](https://github.com/MehVahdJukaar/sleep_tight/assets/88537204/df00dc71-c693-41e1-8321-ff89a5d6f1ea)

![image](https://github.com/MehVahdJukaar/sleep_tight/assets/88537204/844a2976-2c3c-4976-86b2-334d29290658)

The mod shows as compatible with 1.20.1 and I can install it into my 1.20.1 modpack inside curseforge, but when I open the game, it tells me it is 1.20 only?

**Comment by MehVahdJukaar** [comment]
you are using an outdated version
