### ISSUE TITLE
[Suggestion]: Config Option to Make Respawning Occur At Home Beds Only

### ISSUE THREAD

**Issue by CraftyZombie** [MehVahdJukaar/sleep_tight#53]
I know this sounds like a bit of a strange request, but I think it'd be neat if there was a config option that made it so you could only set your spawn point at a bed once it becomes your home bed. It'd be an extra bit of challenge for difficult mod packs.

**Comment by MehVahdJukaar** [comment]
I like that

**Comment by CraftyZombie** [comment]
Thank you for implementing it! Much appreciated. 😁
