### ISSUE TITLE
Sleep Tight Now Crashes With GregTech On Startup

### ISSUE THREAD

**Issue by CraftyZombie** [MehVahdJukaar/sleep_tight#54]
The game crashes on startup with GregTech as of the latest update.

Minecraft: 1.20.1
Forge: 47.2.19
Sleep Tight: 1.20-1.1.13
Moonlight Library: 1.20-2.8.82
GregTech: 1.0.20b

These are the only mods installed.

Crash report: [crash-2024-01-13_17.56.30-client.txt](https://github.com/MehVahdJukaar/sleep_tight/files/13930057/crash-2024-01-13_17.56.30-client.txt)
Latest.log: [latest.log](https://github.com/MehVahdJukaar/sleep_tight/files/13930058/latest.log)
Debug.log: [debug.log](https://github.com/MehVahdJukaar/sleep_tight/files/13930059/debug.log)

**Comment by MehVahdJukaar** [comment]
try new version

**Comment by CraftyZombie** [comment]
Sure, as soon as it uploads on CurseForge.

**Comment by CraftyZombie** [comment]
Fixed, thank you so much!
