### ISSUE TITLE
[BUG] Home Bed Only Config Option Breaks Respawning

### ISSUE THREAD

**Issue by CraftyZombie** [MehVahdJukaar/sleep_tight#57]
When you try to respawn when your spawn point is at a bed when the 'Home Bed Respawn Only' config option is enabled, you can't.

https://github.com/RedPxnda/RespawnObelisks/issues/12

This thread pretty much explains all the details, including logs.

https://github.com/RedPxnda/RespawnObelisks/issues/12#issuecomment-1894614451

**Comment by MehVahdJukaar** [comment]
That's bad ☠️

**Comment by CraftyZombie** [comment]
Sorry, forgot to mention the fix worked. Thank you!
