### ISSUE TITLE
Incompatibility with Ilikewood Mod

### ISSUE THREAD

**Issue by dalekfan** [MehVahdJukaar/sleep_tight#58]
It's so obvious I can literally send you the crash report right here. 
[crash-2024-01-22_10.27.18-fml.txt](https://github.com/MehVahdJukaar/sleep_tight/files/14012393/crash-2024-01-22_10.27.18-fml.txt)
Seems to be caused by a specific mixture of mods, but I do know the issue is between Ilikewood and Sleep Tight. You think you could look into this?

**Comment by dalekfan** [comment]
[crash-2024-01-22_10.55.49-fml.txt](https://github.com/MehVahdJukaar/sleep_tight/files/14012493/crash-2024-01-22_10.55.49-fml.txt)
Got the same crash with less mods this time. Hopefully I can narrow it down a bit.

**Comment by dalekfan** [comment]
Even less.

[crash-2024-01-22_11.00.35-fml.txt](https://github.com/MehVahdJukaar/sleep_tight/files/14012549/crash-2024-01-22_11.00.35-fml.txt)

**Comment by dalekfan** [comment]
[crash-2024-01-22_11.01.53-fml.txt](https://github.com/MehVahdJukaar/sleep_tight/files/14012556/crash-2024-01-22_11.01.53-fml.txt)
And less.

**Comment by MehVahdJukaar** [comment]
wtf. that mod is forcefully early loading my mod configs. Infact they are early loading ALL mods configs. Theres a reason forge loads them after setup and it loads it itself, no need to load them yourself. If one wants to load them early it should only load THEIRS configs.
that is super bad practice and should be reported to them

**Comment by dalekfan** [comment]
> wtf. that mod is forcefully early loading my mod configs. Infact they are early loading ALL mods configs. Theres a reason forge loads them after setup and it loads it itself, no need to load them yourself. If one wants to load them early it should only load THEIRS configs. that is super bad practice and should be reported to them

It seems to only happen with a select group of mods alongside Ilikewood and Sleep Tight. I have tested the two alone before and they work fine, so something is up? Are you sure this is the issue?

**Comment by dalekfan** [comment]
Okay, so I think I might have figured it out. It was somehow caused by Aquaculture Delight, as I didn't have aquaculture installed? Weird bug, but okay. The crash still seems to occur when I install the rest of my modpack as of so far, so I will try and do more investigation.

**Comment by dalekfan** [comment]
This is pretty bad. Ilikewood seems to work with practically all mods, it just seems that SleepTight triggers something. I fear it may be on your end and not Ilikewood's dev, unfortunately, as otherwise I would expect to see this issue much more.

**Comment by MehVahdJukaar** [comment]
thats becasue mods mods just have boolean configs and such. Configs loaded by forge and that is it. The reason why they are loaded later is becasue by then registry objects are present. if one loads them immediately (possibly to affect its own registry object which by itseld is really bad as its conditional registration and will lead to a client not being able to connect to a server with same mods and different configs) things will break as nothing stops one, like me, to use those registry objects in configs. And even if this wanst a thing other mods should NOT mess with other mods own configs or forge itself this way so no its not on my side
