### ISSUE TITLE
Compatibility with Handcrafted?

### ISSUE THREAD

**Issue by FumpleWumper** [MehVahdJukaar/sleep_tight#7]
This mod looks great and I really wanna play with it but I also don't want to abandon Handcrafted, since their furniture looks so much better than vanilla's and has color customization I like playing with. Could it be possible to make it so that this mod works with Handcrafted's beds as well, bed bug infestation and all?

**Comment by MehVahdJukaar** [comment]
Hm i thought it worked already. What parts of it don't work?

**Comment by FumpleWumper** [comment]
Ah I am sorry, it's just that I was reading the mod's page and the only compatibility it mentioned was with Heartstone so I assumed that was the only one, but if it is compatible with Handcrafted then I'll try the mod right away :^D

**Comment by MehVahdJukaar** [comment]
I never tried but generally stuff works together unless proven otherwise. The only thing that it currently does not do is allow bedbugs to go in there but that is just temporarly as i always made it as general as possible like I alsways do
