### ISSUE TITLE
Crashing when sleeping. [Version 1.19.2]

### ISSUE THREAD

**Issue by MoonstruckSpirit** [MehVahdJukaar/sleep_tight#8]
I tried to sleep and it crashed on me. 

Here is the crash log

[crash-2023-03-14_19.56.40-server.txt](https://github.com/MehVahdJukaar/sleep_tight/files/10972748/crash-2023-03-14_19.56.40-server.txt)

**Comment by MehVahdJukaar** [comment]
You are not using the latest version
